config/routes.rb
Rails.application.routes.draw do
  resources :requests
  post "/requests/search" => "requests#search"
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  validates(:name, presence: {messsage: "must not be empty!"})
  validates(:email, {presence: {message: "must not be empty!"}, uniqueness: true})

  def self.recent_ten
    order(created_at: :desc).limit(10)
  end

  def self.search(search_term)
  where(["name ILIKE ? OR email ILIKE ? OR message ILIKE ? OR department ILIKE?", "%#{search_term}%", "%#{search_term}%", "%#{search_term}%", "%#{search_term}%"])
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  REQUESTS_PER_PAGE = 7
  def index
    @requests2 = Request.search(params[:search_term])
    @requests = @requests2.order(created_at: :desc).
                       page(params[:page]).
                       per(REQUESTS_PER_PAGE)
  end

  def new
    @request = Request.new
  end

  def create
    request_params = params.require(:request).permit(:name, :email, :department, :message)
    @request = Request.new request_params
      if @request.save
        redirect_to requests_path
      else
        render :new
      end
  end

  def show
    @request = Request.find params[:id]
    @requests2 = Request.search(params[:search_term])
    @requests = @requests2.order(created_at: :desc).
                       page(params[:page]).
                       per(REQUESTS_PER_PAGE)
  end

  def destroy
    @request = Request.find params[:id]
    @request.destroy
    redirect_to requests_path
  end

  def edit
    @requests2 = Request.find params[:id]
  end

  def update
    @requests2 = Request.find params[:id]
    request_params = params.require(:request).permit([:name, :email, :department, :message])
      if @requests2.update request_params
        redirect_to request_path(@requests2)
      else
        p @requests2.errors.full_messages.join(", ")

        render :edit
      end
  end

  def search
    if params[:search_term]
      query = "%#{params[:search_term]}%"
      @requests = Request.where(
      "name ILIKE :search_term OR department ILIKE :search_term",
       {search_term: query}
      )
    else
      @requests = Request.all
    end
     render :index
  end
end

app/controllers/support_requests_controller.rb
class SupportRequestsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/support_requests_helper.rb
module SupportRequestsHelper
end

app/views/application/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Support Page</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Home", root_path %>
  <%= link_to "Create a Request", new_request_path %>
  <%= link_to "All Requests", requests_path %>

  <br>


<%= yield %>

</body>
</html>

app/views/home/index.html.erb
<div class="container">
<h1>Welcome!</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-sprockets.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
    <div class="container">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Create New Request", new_request_path %></li>
      <li><%= link_to "All Requests", requests_path %></li>
    </ul>

    <!-- <div class="navbar-form navbar-right">
      <div class="form-group">
        <%= form_tag("/requests/search", method: :get) %>
        <%= text_field_tag 'search_term' %>
      </div>
    <%= submit_tag 'search', class:'btn btn-default' %>
    </div> -->
<div class="navbar-form navbar-right">
<%= form_tag requests_path, :method => 'get' do %>
<%= text_field_tag :search_term, params[:search_term], class: 'form-control' %>
<%= submit_tag "Search", class: 'btn btn-default'%>
<!-- <%# submit_tag "Search", :name => nil %> why is there :name => nil ? I don't know-->
<% end %>
</div>
    <!-- <form class="navbar-form navbar-right" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form> -->

    </div>
    </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/requests/edit.html.erb
<div class="container">
<h1>Edit Request</h1>
<hr>
<%= @requests2.errors.full_messages.join(", ") %>

<%= form_for @requests2 do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>
<div>
  <%= f.label :email %>
  <%= f.text_area :email, class: 'form-control' %>
</div>
<div>
  <%= f.label :department %>: Sales
  <%= f.radio_button :department, "Sales" %>&nbsp;|
  Marketing <%= f.radio_button :department, "Marketing" %>&nbsp;| Technical
  <%= f.radio_button :department, "Technical" %>
</div>
<div>
  <%= f.label :message %>
  <%= f.text_field :message, class: 'form-control' %>
</div>
  <%= f.submit %>
  <% end %>
</div>

app/views/requests/index.html.erb
<div class="container">
<h1>Support Requests</h1>
<hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Department</th>
      <th>Message</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @requests.each do |request| %>
    <tr>
      <td><%= request.name %></td>
      <td><%= request.email %></td>
      <td><%= request.department %></td>
      <td><%= request.message %></td>
      <td>
        <%= link_to "Edit", edit_request_path(request) %> |
        <%= link_to "Delete", request_path(request), method: :delete, data: {confirm: "are you sure?"}%>
      </td>

    </tr>
    <% end %>
  </tbody>
</table>
<div class="digg_pagination">
<%= paginate @requests %>
</div>
</div>

app/views/requests/new.html.erb
<div class="container">
<%= @request.errors.full_messages.join(", ") %>

<h1>Create new request</h1>
<hr>
<%= form_for @request do |f| %>
<div>
  <%= f.label :name %>*
  <%= f.text_field :name, class: 'form-control' %>
</div>
<br>
<div>
  <%= f.label :email %>*
  <%= f.text_field :email, class: 'form-control'%>
</div>
<br>
<div>
  <%= f.label :department %>: Sales
  <%= f.radio_button :department, "Sales" %>&nbsp;|
  Marketing <%= f.radio_button :department, "Marketing" %>&nbsp;| Technical
  <%= f.radio_button :department, "Technical" %>
</div>
<br>
<div>
  <%= f.label :message %>
  <%= f.text_area :message, class: 'form-control', rows: '5' %>
</div>
<br>
<div class="container">
<%= f.submit %>
<% end %>
</div>
</div>

app/views/requests/show.html.erb
<div class="container">
<h3><%= @request.name %></h3>
<p><%= @request.email %></p>
<p><%= @request.message %></p>
<p><%= @request.department %></p>

<%= link_to "Edit", edit_request_path(@request) %>
<%= link_to "Delete", request_path(@request),
                      method: :delete,
                      data: {confirm: "Are you sure?"}%>
</div>